#+TITLE:    OpenWrt Docker x86_64 Image
#+AUTHOR:   Kambiz Darabi
#+EMAIL:    darabi@m-creations.net
#+DATE: \today
#+TAGS: { export noexport }
#+STARTUP: hidestars
#+STARTUP: overview
#+OPTIONS: ^:{}


* Introduction

This document gathers all information about the build process for a
reliable build and distribution of a x86_64 base image and
corresponding packages.

The docker base image can be found at

https://registry.hub.docker.com/u/mcreations/openwrt-x64/

* Development Process

To be able to provide consistent binaries, tags are created with
format `vYYYYMMDD` (year-month-day).

In contrast to the trunk version of openwrt, the package feeds are
already incorporated in this repo and don't need to be updated from
their respective git repositories. Therefore it is **forbidden** to
use `./scripts/feeds update` without the `-i` option: only indexing of
the feeds is allowed.

The current configuration for the build is kept in
m-creations/config-x86_64.

* Build Process

The build process uses the mentioned m-creations/config-x86_64 as
.config, then starts a build which creates the base images and all
packages.

** Build all packages

```
cp m-creations/config-x86_64 .config
./scripts/feeds update -i
(date > build.log && make  V=s && date) 2>&1 | tee -a build.log
```

** Update the feed subtrees

The feed subtrees were added with:

```
git remote add feed-packages https://github.com/openwrt/packages.git
git subtree add --squash --prefix=feeds/packages feed-packages master

git remote add feed-luci https://github.com/openwrt/luci.git
git subtree add --squash --prefix=feeds/luci feed-luci master

git remote add feed-routing https://github.com/openwrt-routing/packages.git
git subtree add --squash --prefix=feeds/routing feed-routing master

git remote add feed-telephony http://git.openwrt.org/feed/telephony.git
git subtree add --squash --prefix=feeds/telephony feed-telephony master

git remote add feed-management https://github.com/openwrt-management/packages.git
git subtree add --squash --prefix=feeds/management feed-management master
```

With these commands the feeds are updated to the master of those repos:

```
for f in packages luci routing telephony management ; do
  echo git subtree pull —prefix=feeds/$f —squash feed-$f master
done

./scripts/feeds update -i
./scripts/feeds install -a
```

If it becomes necessary to patch the feed repos, one can easily
redefine the feed-<feedname> remote repository URLs.

